### ISSUE TITLE
My Android Studio got stuck when load this project

### ISSUE THREAD

**Issue by thinkhy** [udacity/ud825-compute-and-memory#5]
The version of Android Studio is 2.23. Anyone hit the same issue?

**Comment by thinkhy** [comment]
Resolved the problem  as following:
 
    * Start Android Studio and create a project
    * From menu select File > New > Import module
    * Select the app directory in project "Computer" 
    *  Build the module "Computer" in the new project

**Comment by u3shadow** [comment]
it works for me, thanks a lot
